print(30*"-")
print("Faça Sua Inscrição!")
print(30*"-")
nome = input('Qual é o seu nome?')
email = input('Qual o seu email?')
escola = input('Qual a sua escola?')
print(30*'-')
print('Está feito!')
print(30*'-')
print(f'Usuario(a): {nome}')
print(f'Email: {email}')
print(f'Escola: {escola}')